# Automatic Datatypes

In [1]:
import numpy as np
a = np.array([1,2,3.5,4,5.5])
print(a)
print(a.dtype)

[1.  2.  3.5 4.  5.5]
float64


# Zeros

In [2]:
import numpy as np
a = np.zeros([5])
print(a)

[0. 0. 0. 0. 0.]


# Integer zeros

In [3]:
import numpy as np
arr = np.zeros(5, dtype=int)
print(arr)

[0 0 0 0 0]


In [4]:
# 2d zero
import numpy as np
a = np.zeros((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
