# Np.ones

In [1]:
# create an array filled with ones

import numpy as np
arr = np.ones(5, dtype =int)
print(arr)

[1 1 1 1 1]


In [ ]:
# create an array filled with ones

import numpy as np
arr = np.ones((2,2))
print(arr)

# np.empty()

In [3]:
# create an array without initializing its elements

import numpy as np
arr= np.empty(5)
print(arr)

[6.23042070e-307 4.67296746e-307 1.69121096e-306 1.86921822e-306
 5.68175493e-322]


In [1]:
import numpy as np
arr= np.empty(5)
arr[:]=[1,2,3,4,5]
print(arr)

[1. 2. 3. 4. 5.]


# np.full()

In [ ]:
# create an array where every elements has the same value, provided by the user

import numpy as np
arr = np.full(5,7)
print(arr)

In [2]:
import numpy as np
arr = np.full((3,3),7)
print(arr)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


# np.eye()

In [5]:
# create a identical like matrix where the main diagonal is 1 and all other elements are 0

import numpy as np
arr = np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [4]:
import numpy as np
arr = np.eye(3,5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


# np.identity()

In [7]:
import numpy as np
arr =np.identity(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
