# Numpy

In [ ]:
# marks=[10,20,30,40,50]
import numpy as np
print(np.__version__)

# Numpy array

In [ ]:
import numpy as np
numbers=np.array([1,2,3,4,5])
print(numbers)
print(type(numbers))

# Automatic Datatypes

In [1]:
import numpy as np
a = np.array([1,2,3.5,4,5.5])
print(a)
print(a.dtype)

[1.  2.  3.5 4.  5.5]
float64


# Zeros

In [2]:
import numpy as np
a = np.zeros([5])
print(a)

[0. 0. 0. 0. 0.]


# Integer zeros

In [1]:
import numpy as np
arr = np.zeros(5, dtype=int)
print(arr)

[0 0 0 0 0]


In [ ]:
# 2d zero
import numpy as np
a = np.zeros((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# Np.ones

In [3]:
# create an array filled with ones

import numpy as np
arr = np.ones(5, dtype =int)
print(arr)

[1 1 1 1 1]


In [4]:
# create an array filled with ones

import numpy as np
arr = np.ones((2,2))
print(arr)

[[1. 1.]
 [1. 1.]]


# np.empty()

In [ ]:
# create an array without initializing its elements

import numpy as np
arr= np.empty(5)
print(arr)

[5.e-324 5.e-324 5.e-324 5.e-324 5.e-324]


In [6]:
import numpy as np
arr= np.empty(5)
arr[:]=[1,2,3,4,5]
print(arr)

[1. 2. 3. 4. 5.]


# np.full()

In [7]:
# create an array where every elements has the same value, provided by the user

import numpy as np
arr = np.full(5,7)
print(arr)

[7 7 7 7 7]


In [16]:
import numpy as np
arr = np.full((3,3),7)
print(arr)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


# np.eye()

In [12]:
# create a identical like matrix where the main diagonal is 1 and all other elements are 0

import numpy as np
arr = np.eye(3,5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


# np.identity()

In [15]:
# create 
import numpy as np
arr =np.identity(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
